#!/bin/bash

echo "Enter a string:"
read input_string

input_string=$(echo "$input_string" | tr '[:upper:]' '[:lower:]')

vowel_count=0

for (( i=0; i<${#input_string}; i++ ))
do
    
    current_char=${input_string:i:1}

    if [[ $current_char == [aeiou] ]]
    then
        ((vowel_count++))
    fi
done

echo "Number of vowels: $vowel_count"
//output 
Enter a string:
Hello, world!
Number of vowels: 3










