#!/bin/bash

echo "Enter a string:"
read input

input=$(echo "$input" | tr -dc '[:alnum:]')

reverse=$(echo "$input" | rev)


if [ "$input" = "$reverse" ]; then
    echo "The string is a palindrome."
else
    echo "The string is not a palindrome."
fi
//output 
Enter a string:
12321

The string is a palindrome.

