#!/bin/bash

echo "Enter the first number: "
read num1

echo "Enter the second number: "
read num2

result=$(echo "scale=2; $num1 / $num2" | bc)

echo "The result of $num1 / $num2 is: $result"

//Output
Enter num1: 10
Enter num2: 3
Result: 3
