#!/bin/bash

echo "Enter the first number: "
read num1

echo "Enter the second number: "
read num2

result=$((num1 + num2)

echo "The result of $num1 + $num2 is: $result"

//RESULT
Enter num1: 15
Enter num2: 12
Result: 27
