#!/bin/bash

echo "Enter the first number: "
read num1
echo "Enter the second number: "
read num2

echo "Before swapping, num1=$num1 and num2=$num2"

temp=$num1
num1=$num2
num2=$temp

echo "After swapping, num1=$num1 and num2=$num2"
//output 
Enter the first number:7
Enter the second number:9
Before swapping, num1=7 and num2=9
After swapping, num1=9 and num2=7
